# Generated by Django 4.2.18 on 2025-01-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blocklistitem_delete_blocklistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='blocklistitem',
            old_name='ip_or_domain',
            new_name='entry',
        ),
        migrations.AddField(
            model_name='blocklistitem',
            name='temp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blocklistitem',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
    ]
