# Generated by Django 4.2.18 on 2025-01-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_domainlist_iplist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocklistitem',
            old_name='temporary',
            new_name='auto_delete',
        ),
        migrations.RenameField(
            model_name='blocklistitem',
            old_name='temp_date',
            new_name='delete_date',
        ),
        migrations.AddField(
            model_name='blocklistitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
