# Generated by Django 4.2.18 on 2025-01-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_temporary_blocklistitem_auto_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistitem',
            name='entry_type',
            field=models.CharField(choices=[('IP', 'IP Address'), ('DOMAIN', 'Domain')], default='IP', max_length=10),
        ),
    ]
