# Generated by Django 4.2.18 on 2025-01-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blocklistitem_entry_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomainList',
        ),
        migrations.DeleteModel(
            name='IPList',
        ),
    ]
