# Generated by Django 4.2.18 on 2025-01-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_domainlist_delete_iplist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocklistitem',
            name='auto_delete',
        ),
    ]
