# Generated by Django 4.2.18 on 2025-01-23 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_blocklistitem_auto_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistitem',
            name='auto_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blocklistitem',
            name='delete_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
