# Generated by Django 5.1.6 on 2025-02-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_blocklistitem_auto_delete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocklistitem',
            name='auto_delete',
        ),
        migrations.RemoveField(
            model_name='blocklistitem',
            name='delete_date',
        ),
    ]
